Description: >
  Danilo Britto / Udacity 2019
  Database :D

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String

  UserName:
    Description: The master user on the database
    Type: String

  Password:
    Description: The password of the master user on the database
    Type: String

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName:
        Ref: DBSubnetGroup
      DBSecurityGroups:
        - Ref: DBSecurityGroup
      AllocatedStorage: "8"
      DBInstanceClass: "db.t2.small"
      Engine: "MySQL"
      MasterUsername: !Ref UserName
      MasterUserPassword: !Ref Password
    DeletionPolicy: "Retain"

  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Allow http to our database
      EC2VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      DBSecurityGroupIngress:
        - EC2SecurityGroupId:
            Fn::ImportValue: !Sub "${EnvironmentName}-WS-SG"

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: description
      SubnetIds:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
        - Fn::ImportValue: !Sub "${EnvironmentName}-PRI1-SN"
        - Fn::ImportValue: !Sub "${EnvironmentName}-PRI2-SN"
